<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Infrastructure implementations (EF Core, Identity, external services)</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ecommerce.Application\Ecommerce.Application.csproj" />
    <ProjectReference Include="..\Ecommerce.Domain\Ecommerce.Domain.csproj" />
  </ItemGroup>
</Project>
