<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <Description>Integration tests (Api + Infrastructure)</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Ecommerce.Api\Ecommerce.Api.csproj" />
    <ProjectReference Include="..\..\src\Ecommerce.Infrastructure\Ecommerce.Infrastructure.csproj" />
  </ItemGroup>
</Project>
