<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <Description>Application unit tests</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Ecommerce.Application\Ecommerce.Application.csproj" />
  </ItemGroup>
</Project>
